// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package user

import (
	_ "gf_user_task/internal/logic/user/smc"
)
